definitions:
  Controllers.Success:
    properties:
      current_page:
        type: integer
      data:
        items:
          $ref: '#/definitions/client.KeyRates'
        type: array
      from_date:
        type: string
      per_page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  client.KeyRates:
    properties:
      date:
        type: string
      rate:
        type: string
    type: object
info:
  contact: {}
paths:
  /keyrate:
    get:
      description: Return keyrates
      parameters:
      - description: return keyrates from date
        format: "2006-01-02"
        in: query
        name: from_date
        type: string
      - description: Page number
        format: "2"
        in: query
        name: page
        type: integer
      - description: Key rates per page
        format: "10"
        in: query
        name: per_page
        type: integer
      - description: Force get last key rate. Max count retry 5
        format: "1"
        in: query
        name: last_key_rate
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Controllers.Success'
            type: array
        "400":
          description: Bad Request
          schema:
            type: error
        "404":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            type: error
      summary: Show key rates
      tags:
      - keyrate
swagger: "2.0"
